/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GpuMetrics {
  gpuUtilization: number
  temperature: number
  powerUsage: number
  name: string
  id: string
  constructor(gpuUtilization: number, temperature: number, powerUsage: number, name: string, id: string)
  static getMetrics(interval: number): GpuMetrics
}
